#!/bin/sh 

# Starts a tracker
# Note: this computer will run the tracker webserver, host the torrents,
# and seed the files.

# Set environment variables
source flowcopy_env

# Be sure the Torrent directory exists
mkdir "$TORRENT_DIR" > /dev/null 2>&1

# Clean up.  (Not every user will be interested.)
# Remove the download info file -- it may be from a previous location/invocation
rm "$DOWNLOAD_INFO_FILE" > /dev/null 2>&1
# Be sure there are no old torrents hanging around
rm "$TORRENT_DIR/*.torrent" > /dev/null 2>&1


echo
echo "Flowcopy tracker running on http://$MYIPADDRESS:$PORT"
echo

# Start the tracker
$PYTHON "$BITTORNADO_DIR/bttrack.py" \
    --port $PORT --dfile "$DOWNLOAD_INFO_FILE" \
    --allow_get 1 --show_names 1 \
    --allowed_dir "$TORRENT_DIR" \
    --parse_dir_interval 5 \
    --timeout_downloaders_interval 120 \
    --reannounce_interval 15 \
    --response_size 500 \
    --nat_check 0 
    
