#!/bin/sh

# Set environment variables
source flowcopy_env

# Check that a tracker is already running
if [ `"$CURL" --silent "$MYIPADDRESS:$PORT" | grep -c "BitTornado"` == "0" ] ; then
    echo "Could not find a tracker running on this computer."
    echo "Please run flowcopy_start_tracker, and then re-issue this command."
    exit 1
fi

# Input: Path of the file to host
FILE="$1"
if [ -z "$FILE" ] ; then echo "Please specify the name of the file you'd like to host" ; exit 1 ; fi

TORRENT_FILE_NAME="$TORRENT_DIR/`basename $FILE`.torrent"
echo $TORRENT_FILE_NAME

echo "Scanning file"

# Create a .torrent file for this file, and store it in the torrents directory
$PYTHON "$BITTORNADO_DIR/btmakemetafile.py" \
    http://$MYIPADDRESS:$PORT/announce \
    $FILE --target "$TORRENT_FILE_NAME"
    
echo "Waiting for tracker to see the new .torrent file"
sleep 10    # tracker checks every 5 seconds

# Now, seed the file
$PYTHON "$BITTORNADO_DIR/btdownloadcurses.py" \
    --responsefile "$TORRENT_FILE_NAME" \
    --saveas "$FILE" \
    --ip "$MYIPADDRESS"
    --upnp_nat_access 0 \
    --max-uploads 1 \
    --timeout 2.0 --timeout_check_interval 1.0 \
    --rerequest_interval 15 http_timeout 5 \
    --write_buffer_size 16 --snub_time 10 \
    --security 0 --max_connections 64 --double_check 0 --lock_files 0 

# --max_upload_rate 10240 --max_download_rate 10240



